version: '3.8'

services:
  db:
    image: postgres:18
    container_name: sql_quest_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER_ADMIN}
      POSTGRES_PASSWORD: ${DB_PASS_ADMIN}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5435:5432'
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
